Added routing and filtering for /api/plugins
MoDNS/MoDNS pull request #23
Opened 2023-03-29 22:57 UTC by SethajWarren

2023-03-29 23:25 UTC, carterray31001 approved these changes

2023-03-30 17:37 UTC, bpjordan requested changes
See comment on `plugins/metadata.rs`

2023-03-30 17:37 UTC, bpjordan commented on server/src/plugins/metadata.rs
#21 includes getters for metadata values that would make it easier to handle checking for modules & other metadata on a plugin. I would prefer if you waited until #21 gets merged and use that instead of adding checks directly to the `PluginManager`, to maintain separation of concerns.

I.e., to filter out only plugins with listeners, you can do

```rust
PM.list_metadata().filter(|(_, metadata)| metadata.is_listener())
```

2023-03-30 17:37 UTC, bpjordan commented on server/src/listeners/api/routes.rs
> +    let metadata = pm.read().await.list_metadata();
See comment below on how this function can get cleaned up

2023-03-31 18:50 UTC, AankitP approved these changes
when the gods created you, they made sure to use all of the sugar and spice

2023-03-31 18:57 UTC, bpjordan approved these changes

2023-03-31 18:59 UTC, merged